# Generated by Django 4.0.2 on 2022-04-25 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInc', models.IntegerField()),
                ('idSeq', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('rh', models.FloatField()),
                ('rhSensor', models.FloatField()),
                ('eggTurned', models.BooleanField()),
                ('incTime', models.CharField(max_length=100)),
                ('recieved', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserIncubator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incubator', models.IntegerField()),
                ('made', models.DateTimeField(default=django.utils.timezone.now)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addedBy', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
